/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 red_heart3.glb --transform 
Files: red_heart3.glb [126.12KB] > /Users/maya/Desktop/MyProjects/maya-wright/public/red_heart3-transformed.glb [7.02KB] (94%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function RedHeart(props) {
  const { nodes, materials } = useGLTF('/red_heart-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.165, 0.02, 0.165]}
        position={[0, 0, -5]}
      >
        <mesh
          geometry={nodes.Cube067.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube067_1.geometry}
          material={materials['Material.006']}
        />
        <mesh
          geometry={nodes.Cube067_2.geometry}
          material={materials['Material.008']}
        />
        <mesh geometry={nodes.Cube067_3.geometry} material={materials.white} />
      </group>
    </group>
  );
}

useGLTF.preload('/red_heart-transformed.glb');

export default RedHeart;
