/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model1.glb --transform 
Files: model1.glb [29.26MB] > /Users/maya/Desktop/MyProjects/maya-wright/public/model1-transformed.glb [25.7MB] (12%)
*/

import React, { useContext, useEffect, useLayoutEffect, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { ModelActionsContext } from '@/app/context/r3f/modelActionsContext';
import { ModelActionsPlaySwitchContext } from '@/app/context/r3f/modelActionsPlaySwitchContext';

const STOP_ANIMATION = 7;

export default function ModelConstructor() {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/model1-transformed.glb');
  const { actions } = useAnimations(animations, group);

  return {
    group,
    nodes,
    materials,
    actions,
  };
}

// export function ModelActions() {
//   const { actions } = ModelConstructor();
//   const [actionsArr, setActionsArr] = useState([]);

//   useLayoutEffect(() => {
//     let actionsSet = new Set();
//     for (const item in actions) {
//       if (item.includes('MAYA_')) {
//         actionsSet.add(item);
//       }
//     }
//     setActionsArr([...actionsSet]);
//   }, [actions]);

//   return actionsArr;
// }