/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model1.glb --transform 
Files: model1.glb [29.26MB] > /Users/maya/Desktop/MyProjects/maya-wright/public/model1-transformed.glb [25.7MB] (12%)
*/

import React from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

// const STOP_ANIMATION = 7;

export default function ModelConstructor() {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('/model1-transformed.glb');
  const { actions } = useAnimations(animations, group);

  return {
    group,
    nodes,
    materials,
    actions,
  };
}